### ISSUE TITLE
Ruby 3.1 dry-configurable warning

### ISSUE THREAD

**Issue by skliask** [uploadcare/uploadcare-rails#110]
There is a warning popping up when the gem is used with ruby 3.1.2. 
`<module:ApiStruct>' [dry-configurable] default value as positional argument to settings is deprecated and will be removed in the next major version
Provide a `default:` keyword argument instead`

Looks like an update issue to the dry configurable gem used as a dependency

**Comment by scottsherwood** [comment]
Are there any plans to update the gem so that dry-configurable is no longer needed?

**Comment by rsedykh** [comment]
Hi. Indeed, we're looking for a Ruby dev who can fix this dry-configurable dependency.

There is an issue with Ruby versions and dry-configurable gem, which the bundler can't resolve. Ruby >=3 requires dry-configurable 0.13.0. We have a dirty fix for this case — https://github.com/uploadcare/uploadcare-rails#using-gemfile, but we aren't happy with it. If your app requires another version of dry-configurable, there will be a compatibility issue.

We've currently failed to set up the correct dry-configurable version depending on the Ruby version that will work when installing gem from RubyGems (it worked if you install gems from its repo). When pushed to RubyGems it analyzes gemspec file and fixates dependencies without giving us a chance to set different options. So we've withdrawn Ruby and Rails gems from RubyGems for now and called them Release Candidates.

We see three possible solutions:

1. For apps that require Ruby >=3, install gem from Github: `gem 'uploadcare-rails', git: 'https://github.com/uploadcare/uploadcare-rails.git'`. (First, we have to change `add_development_dependency` to `add_dependency` here https://github.com/uploadcare/uploadcare-ruby/blob/main/uploadcare-ruby.gemspec#L46). But it won't work if your app requires a later version of dry-configurable'. This is equal to the current solution published in the readme.

2. Create a separate gem for Ruby >=3. We don't like this either.

3. The best solution is to understand those syntax issues and make a monkey patch or an adapter.

Can somebody help us with the last one?

**Comment by abhishekgupta5** [comment]
Would be happy to help on this.

**Comment by rsedykh** [comment]
> Would be happy to help on this.

I'm all ears. You can email me on rsedykh@uploadcare.com

**Comment by kraft001** [comment]
@skliask Fixed in the new version (3.3). Please, try it

@scottsherwood Yes, the gem was updated. It still depends on `dry-configurable`, but now it uses the most recent versions and runs without issues. Please, check it
