### ISSUE TITLE
Set data-multiple on field helper

### ISSUE THREAD

**Issue by jjf21** [uploadcare/uploadcare-rails#119]
### Brief description of the feature and motivation behind it
Hey, it would be nice to be able to pass the `multiple: false` to the field helper, to force the single/multiple files select, rather than depend on the attribute name

Might be nice that `options[:multiple]` has priority on `uploadcare_uploader_multiple?`  here:
https://github.com/uploadcare/uploadcare-rails/blob/main/lib/uploadcare/rails/action_view/uploadcare_uploader_tags.rb#L31

What do you think?

**Comment by kraft001** [comment]
@jjf21 Thank you for the idea!
The feature was added to the new version 3.3.1. Please, try it

**Comment by jjf21** [comment]
Hello @kraft001, thanks it's working perfectly ! 👌

**Comment by jjf21** [comment]
@kraft001 Unfortunatly we have a problem.

The `mount_uploadcare_file_group.rb` is using the`GROUP_ID_REGEX` to set a the `group_id`, but it's not matcing. While single file does not match this regex. It should use the default regex in `IdExtractor` =>  `/\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b/`

Resulting in
```
Uploadcare::Exception::RequestError
group_id is required.
```

**Comment by kraft001** [comment]
@jjf21 Thank you for the bug report!
The issue seems to be unrelated to the suggested feature (`options[:multiple]`), it would be great to create a new Github issue.
I'm not sure how I can replicate the error `Uploadcare::Exception::RequestError
group_id is required.`, could you describe the steps you took?
