### ISSUE TITLE
Use non-cdn urls with the widget

### ISSUE THREAD

**Issue by jjf21** [uploadcare/uploadcare-rails#129]
### Question

We have a model where the attachment `receipt_url` is a AWS S3 url.
We would like to use the uploadcare-widget with this url. But as far as I understand the uploadcare-widget is only working with uploadcare cdn urls.

My question is:
Could the uploadcare-widget (single-file) be mounted with a non-cdn url ? (right now it says "Incorrect Value")

Thanks !

**Comment by optlsnd** [comment]
Hi @jjf21 , you can use the widget's API to programmatically upload a file from an S3 URL and feed the upload to the widget as a default value:

```js
const url = "https://acme.com/image.jpg";
const widget = uploadcare.Widget("[role=uploadcare-uploader]");

const file = uploadcare.fileFrom("url", URL, {
  publicKey: "YOUR_PUBLIC_KEY"
});

widget.value(file);
```
