### ISSUE TITLE
Wrong tag for cdn inclusion in README file

### ISSUE THREAD

**Issue by stavros-souvatzis** [uploadcare/uploadcare-rails#130]
### Describe the bug

In Readme file, we are instructed to use `uploadcare_widget_tag`, which appears to be undefined. By searching in the code, the correct tag to use is `uploadcare_include_tag`. Please, update the instructions accordingly.

### Environment

 - Library version: 3.3.4
 - Language/framework version: Ruby 3.0.2, Rails 7.0.1
 - OS version: Debian 11.6

![image](https://github.com/uploadcare/uploadcare-rails/assets/89575085/310e05e9-420f-47c1-a389-6b1e0df6d310)

**Comment by vipulnsward** [comment]
Fixed in https://github.com/uploadcare/uploadcare-rails/commit/94268eff21f5b0704f4bc1bd036e0762e800540d and 3.4.0 release.
