### ISSUE TITLE
Duplicate button

### ISSUE THREAD

**Issue by rockshell** [uploadcare/uploadcare-rails#134]
Passed on from general support

> We on a Rails application (version 7.0.8) with the gem uploadcare-rails (version 3.3.4) and we're facing a strange behavior with the uploadcare_uploader_field helper :

When I hit the back button of the browser, the page is rendered and the Document buttons appears twice.

I can't figure out why. Do you have any idea?

![image](https://github.com/uploadcare/uploadcare-ruby/assets/16293580/ed41adc5-086a-4171-a8ab-ff05150c160c)
![image](https://github.com/uploadcare/uploadcare-ruby/assets/16293580/8cf454e8-2fda-46bc-9bd6-5da2a6fc80a0)

**Comment by vipulnsward** [comment]
Related bug- https://github.com/uploadcare/uploadcare-widget/issues/328#issuecomment-376139902

**Comment by vipulnsward** [comment]
Going to document the workaround on how others can handle this in their Apps
