### ISSUE TITLE
Error upgrading Rails 7.2

### ISSUE THREAD

**Issue by jjf21** [uploadcare/uploadcare-rails#149]
### Describe the bug

During my Rails upgrade from `7.1.4.1` to `7.2.1.2`, I got an error:
```
     NoMethodError:
       undefined method `assign_attributes' for #<Uploadcare::Rails::Group:0x000000016c9338a8>
```

After some research, it looks like `Uploadcare::Rails::Group` rely on the method `assign_attributes` which is defined in [ActiveModel::AttributesAssignment](https://github.com/rails/rails/blob/32dcdcaef666e0043b0df844aa167201d50f8c9c/activemodel/lib/active_model/attribute_assignment.rb#L28). 

`Uploadcare::Rails::Group` includes `Objects::Loadable` which includes `ActiveRecord::AttributeAssignment`.

Method `assign_attributes` is not `ActiveRecord`'s responsability therefore it has been remove from [ActiveRecord::AttributeAssignment](https://github.com/rails/rails/commit/2c57ec6a179e5fb851aca1bdc4b11b17d99a93c8)

Since `ActiveModel::AttributesAssignment` is no more included in `ActiveRecord::AttributeAssignment` the method `assign_attributes` is undefined.

# EDIT
It looks like it has been fix for you main branch https://github.com/uploadcare/uploadcare-rails/commit/cbf92458e21539b3fcbd8b3b09fc68d27a72c221 but hasn't been released.

**Comment by vipulnsward** [comment]
Will publish a new release soon.

**Comment by jjf21** [comment]
It works, thanks for reactivity !
