### ISSUE TITLE
Conflict when installing with activeadmin

### ISSUE THREAD

**Issue by eric-moore** [uploadcare/uploadcare-rails#21]
When installing this gem with activeadmin gem, css and js files for activeadmin are no longer generated.  I saw a few posts around the net so figured I would post an issue here as it seemed they were just abandoning this tool for another.

Basically if you do a Rails 4 app from scratch with just devise, activeadmin, and uploadcare-care gems the css and js are not rendered as the uploadcare-gem.  It appears to be something with the js_include_tag and css_include_tag being overwritten and spitting out a /stylesheets and /javascripts path.  

If you comment out the uploadcare gem, bundle install, it will then show /assets path and all works again.

Not sure if you were aware, but seems to be an issue for those using the popular admin backend in rails.

**Comment by dmitry-mukhin** [comment]
thanks! we'll look into it

**Comment by dmitry-mukhin** [comment]
@romanonthego any chance you could take a looksie?

**Comment by Mik-die** [comment]
got same issue yesterday :+1:

**Comment by romanonthego** [comment]
thanks again @Mik-die for you pull request.
@eric-moore - I could not replicated the problem, active_admin.css, active_admin.js (and many others assets files) generated and served without a problem on clean project with rails 4.1.6, devise and 1.0.0.pre active_admin. I hope pull request from @Mik-die solve your problem, please try version 1.0.6 of uploadcare_rails gem (or just reference github repo) and write us back :)

**Comment by dmitry-mukhin** [comment]
@eric-moore, can you confirm that version 1.0.6 solves this issue?

**Comment by eric-moore** [comment]
We wrote a monkey patch on our side that fixes it.  I will test the new version today and let you know.  Thanks

**Comment by dmitry-mukhin** [comment]
@eric-moore please share the patch, if new version still has the issue.
Thanks!

**Comment by rastyagaev** [comment]
Tested with rails@4 and activeadmin@1.3, it works well with uploadcare-rails@1.2 without any bugs.
