### ISSUE TITLE
How to fix the crop size without upscale or minimum option

### ISSUE THREAD

**Issue by djalmaaraujo** [uploadcare/uploadcare-rails#25]
I want to crop for example 100x250 and nothing else more, just 100x250, how can I configure like this? The documentation is not very clear.

**Comment by dmitry-mukhin** [comment]
Hey,

take a look at this: https://uploadcare.com/documentation/widget/#crop

I don't think this is relevant in this repo, please ask in https://github.com/uploadcare/uploadcare-widget or at help@uploadcare.com
