### ISSUE TITLE
Show uploader box without modal box

### ISSUE THREAD

**Issue by fabdelgado** [uploadcare/uploadcare-rails#28]
I would like to show embedded in the html box as shown in the following attachment.

![export](https://cloud.githubusercontent.com/assets/8621547/9591690/97ffe15a-5013-11e5-8413-1d471355962a.png)

Using in _from.html.erb

<%= f.uploadcare_field :file %>

Any idea how to do this?

Thankyou

**Comment by dmitry-mukhin** [comment]
not sure if this is achievable via erb at the moment.
I would suggest to use plain HTML
