### ISSUE TITLE
Chrome Inspector Breaks With Widget Version 2.6

### ISSUE THREAD

**Issue by ygamretuta** [uploadcare/uploadcare-rails#32]
I used a 1.5 version of the widget before. Working as expected.

I transferred to 2.5:

https://ucarecdn.com/widget/2.6.0/uploadcare/uploadcare.full.min.js

and Chrome inspector breaks.

When I try to uncheck style boxes, the boxes just blink without uncheck-ing

I have another project where it does that. I investigated and "something" seems to be applying the same classes to the `html` DOM element over and over again. The classes are `js` and `csstransitions`

**Comment by dmitry-mukhin** [comment]
This is known "issue":
http://stackoverflow.com/a/32926475/253146

Just add an ID to HTML tag or disable live initialization.
