### ISSUE TITLE
Initializer failing in Rails 4 beta

### ISSUE THREAD

**Issue by adamrobbie** [uploadcare/uploadcare-rails#4]
Following README example:
the initializer is throwing method_missing errors

stack trace as follows:
/Users/adamrobbie/Code/Ruby/regionals/vendor/bundle/gems/railties-4.0.0.beta1/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method`uploadcare' for #Rails::Engine::Configuration:0x007fe7cd886758 (NoMethodError)
    from /Users/adamrobbie/Code/Ruby/regionals/config/initializers/uploadcare.rb:2:in `block in <top (required)>'
    from /Users/adamrobbie/Code/Ruby/regionals/vendor/bundle/gems/railties-4.0.0.beta1/lib/rails/railtie/configurable.rb:24:in`class_eval'
    from /Users/adamrobbie/Code/Ruby/regionals/vendor/bundle/gems/railties-4.0.0.beta1/lib/rails/railtie/configurable.rb:24:in `configure'
    from /Users/adamrobbie/Code/Ruby/regionals/config/initializers/uploadcare.rb:1:in`<top (required)>'
    from /Users/adamrobbie/Code/Ruby/regionals/vendor/bundle/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:222:in `load'
    from /Users/adamrobbie/Code/Ruby/regionals/vendor/bundle/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:222:in`block in load'
    from /Users/adamrobbie/Code/Ruby/regionals/vendor/bundle/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/adamrobbie/Code/Ruby/regionals/vendor/bundle/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:222:in`load'
    from /Users/adamrobbie/Code/Ruby/regionals/vendor/bundle/gems/railties-4.0.0.beta1/lib/rails/engine.rb:608:in `block (2 levels) in class:Engine'

**Comment by rastyagaev** [comment]
It works well with last 4.0 rails (4.0.13). This issue is outdated.
