### ISSUE TITLE
Release gem to Rubygems

### ISSUE THREAD

**Issue by shaneog** [uploadcare/uploadcare-rails#41]
Since the new version was updated here, it hasn't been uploaded to Rubygems.

https://rubygems.org/gems/uploadcare-rails

**Comment by dmitry-mukhin** [comment]
after some struggle I've managed to push new gem version.
could you check that it's correct?

thanks!

**Comment by shaneog** [comment]
Looks good, thanks!
I recommend adding the Rubygem deployment to Travis based on git tags: https://docs.travis-ci.com/user/deployment/rubygems

Just run `travis setup rubygems` to setup.
