### ISSUE TITLE
Rails 5.1 Deprecation Warning 

### ISSUE THREAD

**Issue by matbrady** [uploadcare/uploadcare-rails#49]
I'm getting the following warning:
```
DEPRECATION WARNING: Passing string to define callback is deprecated and will be removed in Rails 5.1 without replacement.
```
for including: 
```
has_uploadcare_file :file
```

**Comment by dmitry-mukhin** [comment]
classic ruby breaking backwards compatibility in minor versions :(

**Comment by brandoncordell** [comment]
Rails 5.1.0.rc1 throws an ArgumentError now instead of a deprecation warning.

**Comment by dmitry-mukhin** [comment]
@brandoncordell @matbrady is there a recommended way to address the issue?

**Comment by brandoncordell** [comment]
@dmitry-mukhin Yes, I'm about to open a pull request for it. I don't know how quickly they'll get to merging it though.

**Comment by brandoncordell** [comment]
@dmitry-mukhin @matbrady 

I've opened a [pull request](https://github.com/uploadcare/uploadcare-rails/pull/51) for this.

You can see what's been changed in my branch to make it work so far.

**Comment by dmitry-mukhin** [comment]
thanks!

**Comment by f6v** [comment]
@dmitry-mukhin so this is closed, right? Or is it still an issue?

**Comment by vizvamitra** [comment]
@f6v right, thank you for noticing
