### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by f6v** [uploadcare/uploadcare-rails#59]
Is image preview described [here](https://uploadcare.com/cookbook/widget_visual/#uploaded-image-preview) supported by the gem?

**Comment by dmitry-mukhin** [comment]
That is an example of how you can use image preview.
It is only one of many ways to achieve previews, and depending on your business logic you can use it verbatim or just do something similar that makes sense for your case.

Hence, there is no point to implement something like this in the gem (or any other client library).

Let us know if that makes sense or not.
