### ISSUE TITLE
Any support for Rails 5.2.0 yet?

### ISSUE THREAD

**Issue by antwonlee** [uploadcare/uploadcare-rails#65]
`uploadcare-rails (= 1.1.1) was resolved to 1.1.1, which depends on rails (< 5.2, >= 4)`

Any updates on this for Rails?

**Comment by dmitry-mukhin** [comment]
[Apparently](https://github.com/uploadcare/uploadcare-rails/pull/64#issuecomment-382437161), you can use the gem almost as is with 5.2 right now.

Please watch #66 for proper gem update.

**Comment by antwonlee** [comment]
Thanks @dmitry-mukhin

**Comment by dmitry-mukhin** [comment]
please check out [1.2.0-alpha](https://rubygems.org/gems/uploadcare-rails/versions/1.2.0.pre.alpha)

**Comment by dmitry-mukhin** [comment]
@antwonlee can we close this yet?

**Comment by dmitry-mukhin** [comment]
closed via #66
