### ISSUE TITLE
Typo: marker rather than marked?

### ISSUE THREAD

**Issue by MyklClason** [uploadcare/uploadcare-rails#72]
https://github.com/uploadcare/uploadcare-rails/search?q=marker&unscoped_q=marker

**Comment by MyklClason** [comment]
Also is advanced config:
https://uploadcare.com/documentation/widget/#advanced-configuration 
This now?
https://uploadcare.com/docs/uploads/widget/config/

**Comment by dmitry-mukhin** [comment]
you could send a PR :)

**Comment by dmitry-mukhin** [comment]
fixed in 529b72709acb53102582e9335c99606ea3d8e290 and b8e2c5877136172c76e13226b30a6811f3840fdb

**Comment by dmitry-mukhin** [comment]
@MyklClason Thanks!

**Comment by MyklClason** [comment]
I was going to send a PR until I noticed it was spread over multiple files, which for simple editing would mean two PRs. Good to see it fixed though.
