### ISSUE TITLE
Crop URL not working?

### ISSUE THREAD

**Issue by antwonlee** [uploadcare/uploadcare-rails#75]
<img width="718" alt="operation-url" src="https://user-images.githubusercontent.com/1015604/47133583-f09f3000-d26e-11e8-99e4-89102f73cf31.png">

In my database, the value is stored as `https://ucarecdn.com/34f25e97-45cd-4d29-affd-0b0f5823d69e/-/crop/101x101/800,61/-/preview/`, but when I do something like `object.file.url` in only pulls `https://ucarecdn.com/34f25e97-45cd-4d29-affd-0b0f5823d69e`

What is need is if I do something like `object.file.url` it will give me the cropped version, such as:
`https://ucarecdn.com/34f25e97-45cd-4d29-affd-0b0f5823d69e/-/crop/101x101/800,61/-/preview/`

This was working fine in other Rails app, but current project is not pulling the full url...

**Comment by antwonlee** [comment]
`object.file.url + "-/"+ object.file.operations[0] + "/-/" + object.file.operations[1] + "/"`

I am able to get by doing something like that :point_up: ¯\_(ツ)_/¯

There's got a be a better way I am missing.

**Comment by dmitry-mukhin** [comment]
which gem version are you using?
and do I understand correctly that with older version it did work?

**Comment by antwonlee** [comment]
`uploadcare-rails (1.2.0)`
`uploadcare-ruby (1.2.2)`

I have the same gem versions in my other rails projects that fetche the full url when I do something like `object.file` from the database.

So something like:

`https://ucarecdn.com/34f25e97-45cd-4d29-affd-0b0f5823d69e/-/crop/101x101/800,61/-/preview/`

oppose to something like:

`https://ucarecdn.com/34f25e97-45cd-4d29-affd-0b0f5823d69e`

**Comment by dmitry-mukhin** [comment]
@rastyagaev need assistance)

**Comment by rastyagaev** [comment]
I’ll take a look

**Comment by antwonlee** [comment]
@rastyagaev Any word on this?  Or am I just implementing this wrong?
