### ISSUE TITLE
Uploadcare CDN Certificate is invalid

### ISSUE THREAD

**Issue by stefankp** [uploadcare/uploadcare-rails#83]
Our app can't load the JS for the widget, because the CDN certificate seems to be invalid. 

> Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “ucarecdn.com”, which could put your confidential information at risk.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/3661203/61549292-f1f4c780-aa4f-11e9-8a8d-5662eb2ad741.png">

Can you please fix this?

**Comment by stefankp** [comment]
Seems to be resolved 👍

**Comment by dmitry-mukhin** [comment]
It's an ongoing issue, but this is not a proper channel for this :(
