### ISSUE TITLE
Compatible with Rails 6.0.0?

### ISSUE THREAD

**Issue by antwonlee** [uploadcare/uploadcare-rails#84]
I am trying to upgrade our Rails to 6.0.0.  Is this not compatible with it yet?

**Comment by dmitry-mukhin** [comment]
If it doesn't work out of the box, then it's not compatible.
We'll look into it.

**Comment by antwonlee** [comment]
When I was trying to update Rails to 6.0.0, that's where I hit the problem.

**Comment by stefankp** [comment]
Can you give a timeline fort his? Only gem that prevents us from upgrading to Rails 6.

**Comment by dmitry-mukhin** [comment]
I'm afraid we can't give any public timeline for this.
Any help with PR would be greatly appreciated.

**Comment by jackc** [comment]
FYI, It seems to work just by changing the gemspec to allow Rails 6. I'm only doing simple uploads but so far so good.

**Comment by josefrichter** [comment]
Any update here? The gem doesn't work in Rails 6.1.

**Comment by rsedykh** [comment]
@josefrichter currently no updates. :-( The best solution I can suggest right now is try using http://github.com/uploadcare/uploadcare-ruby-next/ since it's the most fresh one.
